server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: '@Wu20021011'
    url: jdbc:mysql://localhost:3306/lab_scheduler?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  sql:
    init:
      # 是否初始化数据库
      mode: never
#      schema-locations: classpath:init.sql, classpath:data.sql

mybatis:
  mapper-locations: classpath:mappers/*xml
  # 目的是为了省略resultType里的代码量
  type-aliases-package: com.kosthi.labschedulerserver.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
